---
title: Titanic Wrangling
author: Lucas Calaff
jupyter: python3
format:
  html:
    toc: true
    code-fold: true
    theme: darkly
    highlight-style: breezedark
    embed-resources: true
execute:
  enabled: true
---

In this practice activity you'll continue to work with the titanic dataset in ways that flex what you've learned about both data wrangling and data visualization.

```{python}
import pandas as pd
```

```{python}
# Import the titanic dataset here
data_dir = "https://dlsun.github.io/pods/data/"
df_titanic = pd.read_csv(data_dir + "titanic.csv")
```

## 1. Filter the data to include passengers only. Calculate the joint distribution (cross-tab) between a passenger's class and where they embarked.

```{python}
# Code here
df_titanic["class"].value_counts()

df_titanic["type"] = df_titanic["class"].map({
    "1st": "passenger",
    "2nd": "passenger",
    "3rd": "passenger",
    "victualling crew": "crew",
    "engineering crew": "crew",
    "deck crew": "crew", 
    "restaurant staff": "crew"
})

passenger = df_titanic["type"] == "passenger"
df_titanic_passenger = df_titanic[passenger]

pd.crosstab(df_titanic_passenger["class"], df_titanic_passenger["embarked"], normalize = True)
```

## 2. Using the joint distribution that calculated above, calculate the following:

-   the conditional distribution of their class given where they embarked
-   the conditional distribution of where they embarked given their class

Use the conditional distributions that you calculate to answer the following quesitons:

-   What proportion of 3rd class passengers embarked at Southampton?
-   What proportion of Southampton passengers were in 3rd class?

```{python}
# Code here
#columns aka where they embarked in
embarked_class_dist = pd.crosstab(df_titanic_passenger["class"], df_titanic_passenger["embarked"], normalize= "columns")

#index aka what class they are 
class_embarked_dist = pd.crosstab(df_titanic_passenger["class"], df_titanic_passenger["embarked"], normalize = "index")

#proportion of 3rd class in southampton

print(embarked_class_dist["S"])

#proportation of southampton in 3rd class 

class_embarked_dist["S"]
```

## 3. Make a visualization showing the distribution of a passenger's class, given where they embarked.

Discuss the pros and cons of using this visualization versus the distributions you calculated before, to answer the previous questions.

```{python}
# Code here
embarked_class_dist.plot(kind = "bar")
 
```